source 'https://rubygems.org'
ruby "2.0.0"

gem 'sinatra'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
gem "tilt-jbuilder", require: "sinatra/jbuilder"

group :development do
  gem 'rake'
end

group :test do
  gem 'minitest', require: 'minitest/autorun'
  gem 'rack-test'
  gem 'json_expressions', require: 'json_expressions/minitest'
  gem 'database_cleaner'
end
