source 'https://rubygems.org'

gem 'sinatra'
gem "tilt-jbuilder", ">= 0.4.0", :require => "sinatra/jbuilder"
gem "hashie"

group :development do
  gem 'rake'
end

group :test do
  gem 'minitest', require: 'minitest/autorun'
  gem 'rack-test'
end
