source 'https://rubygems.org'
ruby "2.0.0"

gem 'sinatra', ">= 1.1.0"
gem "tilt-jbuilder", ">= 0.4.0", :require => "sinatra/jbuilder"
gem "hashie"
gem 'micro_migrations', github: 'svenfuchs/micro_migrations'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'

group :development do
  gem 'rake'
  gem "activerecord"
end

group :test do
  gem 'minitest', require: 'minitest/autorun'
  gem 'rack-test'
  gem 'json_expressions', require: 'json_expressions/minitest'
  gem 'database_cleaner'
end
